# Generated by Django 3.2.4 on 2021-06-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asciigen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
