# Generated by Django 3.2.4 on 2021-06-25 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asciigen', '0002_alter_query_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='img',
        ),
    ]
