# Generated by Django 3.2.4 on 2021-06-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asciigen', '0003_remove_query_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='img',
            field=models.ImageField(default='/home/avr/Projects/i2ascii/media', upload_to='media'),
        ),
    ]
